package memory

import (
	"context"
	"encoding/json"
	"time"
)

// GovernanceRequest is an ephemeral command input. Event identity and time
// are generated by OMR; callers cannot supply an event id or wall-clock value.
type GovernanceRequest struct {
	Store     *FactStore
	Target    MemoryRef
	Operation string
	Reason    string
	Source    string
	BasisRefs []BasisRef
	Now       time.Time
}

type GovernanceResult struct {
	Status WriteStatus
	Event  GovernanceEvent
}

// BuildGovernanceEvent creates a deterministic append-only event. It does not
// read or write a store; target existence is checked by CommitGovernanceEvent.
func BuildGovernanceEvent(req GovernanceRequest) (GovernanceEvent, error) {
	if err := req.Target.Validate(); err != nil || req.Now.IsZero() {
		return GovernanceEvent{}, storeError(CodeDerivedInvalidInput, "governance request is invalid")
	}
	if req.Operation == "unfreeze" {
		return GovernanceEvent{}, storeError(CodeDerivedInvalidInput, "unfreeze requires evidence re-derivation gate")
	}
	e := GovernanceEvent{SchemaVersion: SchemaVersion, Scope: req.Target.Scope, MemoryID: req.Target.MemoryID, Revision: req.Target.Revision, Operation: req.Operation, Reason: req.Reason, Source: req.Source, BasisRefs: append([]BasisRef(nil), req.BasisRefs...), CreatedAt: req.Now.UTC().Format(time.RFC3339Nano)}
	if err := e.ValidateWithoutID(); err != nil {
		return GovernanceEvent{}, classifyValidateError(err)
	}
	basis, err := canonSlice(e.BasisRefs)
	if err != nil {
		return GovernanceEvent{}, storeError(CodeSchemaInvalid, "governance basis is invalid")
	}
	identity, _ := json.Marshal(map[string]any{"scope": e.Scope, "memory_id": e.MemoryID, "revision": e.Revision, "operation": e.Operation, "reason": e.Reason, "source": e.Source, "basis_refs": basis, "created_at": e.CreatedAt})
	h := hashOf(identity)
	e.EventID = "governance_" + h[len("sha256_"):len("sha256_")+24]
	if err := e.Validate(); err != nil {
		return GovernanceEvent{}, classifyValidateError(err)
	}
	return e, nil
}

// CommitGovernanceEvent appends a safe non-unfreeze event after exact target
// verification. Unfreeze remains explicitly gated until evidence re-derive
// and zero-write failure semantics are implemented.
func CommitGovernanceEvent(ctx context.Context, req GovernanceRequest) (GovernanceResult, error) {
	if req.Store == nil {
		return GovernanceResult{}, storeError(CodeDerivedInvalidInput, "governance store is unavailable")
	}
	e, err := BuildGovernanceEvent(req)
	if err != nil {
		return GovernanceResult{}, err
	}
	b, err := req.Store.Get(ctx, FactKindMemoryRevision, req.Target.MemoryID+"/"+itoa(req.Target.Revision))
	if err != nil {
		return GovernanceResult{}, err
	}
	rev, err := DecodeStrict[MemoryRevision](b)
	if err != nil {
		return GovernanceResult{}, classifyDecodeError(err)
	}
	if rev.ContentSHA256 != req.Target.ContentSHA256 || rev.Scope != req.Target.Scope || rev.MemoryType != req.Target.MemoryType {
		return GovernanceResult{}, storeError(CodeHashMismatch, "governance target does not match stored revision")
	}
	r, err := req.Store.Put(ctx, e)
	if err != nil {
		return GovernanceResult{}, err
	}
	return GovernanceResult{Status: r.Status, Event: e}, nil
}
