package memory

import (
	"context"
	"encoding/json"
	"time"
)

// GovernanceRequest is an ephemeral command input. Event identity and time
// are generated by OMR; callers cannot supply an event id or wall-clock value.
type GovernanceRequest struct {
	Store     *FactStore
	Target    MemoryRef
	Operation string
	Reason    string
	Source    string
	BasisRefs []BasisRef
	Now       time.Time
}

type GovernanceResult struct {
	Status WriteStatus
	Event  GovernanceEvent
}

// BuildGovernanceEvent creates a deterministic append-only event. It does not
// read or write a store; target existence is checked by CommitGovernanceEvent.
func BuildGovernanceEvent(req GovernanceRequest) (GovernanceEvent, error) {
	if err := req.Target.Validate(); err != nil || req.Now.IsZero() {
		return GovernanceEvent{}, storeError(CodeDerivedInvalidInput, "governance request is invalid")
	}
	e := GovernanceEvent{SchemaVersion: SchemaVersion, Scope: req.Target.Scope, MemoryID: req.Target.MemoryID, Revision: req.Target.Revision, Operation: req.Operation, Reason: req.Reason, Source: req.Source, BasisRefs: append([]BasisRef(nil), req.BasisRefs...), CreatedAt: req.Now.UTC().Format(time.RFC3339Nano)}
	if err := e.ValidateWithoutID(); err != nil {
		return GovernanceEvent{}, classifyValidateError(err)
	}
	basis, err := canonSlice(e.BasisRefs)
	if err != nil {
		return GovernanceEvent{}, storeError(CodeSchemaInvalid, "governance basis is invalid")
	}
	identity, _ := json.Marshal(map[string]any{"scope": e.Scope, "memory_id": e.MemoryID, "revision": e.Revision, "operation": e.Operation, "reason": e.Reason, "source": e.Source, "basis_refs": basis, "created_at": e.CreatedAt})
	h := hashOf(identity)
	e.EventID = "governance_" + h[len("sha256_"):len("sha256_")+24]
	if err := e.Validate(); err != nil {
		return GovernanceEvent{}, classifyValidateError(err)
	}
	return e, nil
}

// CommitGovernanceEvent appends an event after exact target verification.
func CommitGovernanceEvent(ctx context.Context, req GovernanceRequest) (GovernanceResult, error) {
	if req.Store == nil {
		return GovernanceResult{}, storeError(CodeDerivedInvalidInput, "governance store is unavailable")
	}
	e, err := BuildGovernanceEvent(req)
	if err != nil {
		return GovernanceResult{}, err
	}
	b, err := req.Store.Get(ctx, FactKindMemoryRevision, req.Target.MemoryID+"/"+itoa(req.Target.Revision))
	if err != nil {
		return GovernanceResult{}, err
	}
	rev, err := DecodeStrict[MemoryRevision](b)
	if err != nil {
		return GovernanceResult{}, classifyDecodeError(err)
	}
	if rev.ContentSHA256 != req.Target.ContentSHA256 || rev.Scope != req.Target.Scope || rev.MemoryType != req.Target.MemoryType {
		return GovernanceResult{}, storeError(CodeHashMismatch, "governance target does not match stored revision")
	}
	if e.Operation == "unfreeze" {
		if err := validateGovernanceBasis(ctx, req.Store, e.Scope, e.BasisRefs); err != nil {
			return GovernanceResult{}, err
		}
		states, err := DeriveState(ctx, req.Store, DerivedStateRequest{Scope: e.Scope, Revision: e.Revision, Now: req.Now})
		if err != nil {
			return GovernanceResult{}, err
		}
		if len(states.States) != 1 || states.States[0].Lifecycle != LifecycleFrozen {
			return GovernanceResult{}, storeError(CodeDerivedInvalidInput, "unfreeze requires a frozen revision")
		}
		evidenceState, err := deriveEvidenceOnly(ctx, req.Store, rev, req.Now)
		if err != nil {
			return GovernanceResult{}, err
		}
		if evidenceState == LifecycleFrozen {
			return GovernanceResult{}, storeError(CodeDerivedInvalidInput, "unfreeze cannot bypass automatic freeze")
		}
	}
	r, err := req.Store.Put(ctx, e)
	if err != nil {
		return GovernanceResult{}, err
	}
	return GovernanceResult{Status: r.Status, Event: e}, nil
}

func deriveEvidenceOnly(ctx context.Context, store *FactStore, rev MemoryRevision, now time.Time) (Lifecycle, error) {
	in, err := loadDerivedInputs(ctx, store)
	if err != nil {
		return "", err
	}
	in.governance = nil
	return deriveOne(ctx, store, in, rev, defaultFreshnessPolicy, now).Lifecycle, nil
}

func validateGovernanceBasis(ctx context.Context, store *FactStore, scope Scope, refs []BasisRef) error {
	for _, b := range refs {
		switch {
		case b.MemoryRef != nil:
			if b.MemoryRef.Scope != scope {
				return storeError(CodeScopeMismatch, "governance basis scope mismatch")
			}
			data, err := store.Get(ctx, FactKindMemoryRevision, b.MemoryRef.MemoryID+"/"+itoa(b.MemoryRef.Revision))
			if err != nil {
				return storeError(CodeDerivedInvalidInput, "governance basis is unavailable")
			}
			r, err := DecodeStrict[MemoryRevision](data)
			if err != nil || r.ContentSHA256 != b.MemoryRef.ContentSHA256 {
				return storeError(CodeDerivedInvalidInput, "governance basis is unavailable")
			}
		case b.JudgmentRef != nil:
			if b.JudgmentRef.Scope != scope {
				return storeError(CodeScopeMismatch, "governance basis scope mismatch")
			}
			data, err := store.Get(ctx, FactKindJudgment, b.JudgmentRef.JudgmentID)
			if err != nil {
				return storeError(CodeDerivedInvalidInput, "governance basis is unavailable")
			}
			j, err := DecodeStrict[JudgmentFact](data)
			if err != nil || j.ContentSHA256 != b.JudgmentRef.ContentSHA256 {
				return storeError(CodeDerivedInvalidInput, "governance basis is unavailable")
			}
		case b.EvidenceRef != nil:
			if b.EvidenceRef.Scope != scope {
				return storeError(CodeScopeMismatch, "governance basis scope mismatch")
			}
			keys, err := store.List(ctx, FactKindMemoryEvidenceGeneration)
			if err != nil {
				return err
			}
			found := false
			for _, key := range keys {
				data, getErr := store.Get(ctx, FactKindMemoryEvidenceGeneration, key)
				if getErr != nil {
					return getErr
				}
				ev, decodeErr := DecodeStrict[MemoryEvidenceGeneration](data)
				if decodeErr != nil {
					return classifyDecodeError(decodeErr)
				}
				for _, er := range ev.EvidenceRefs {
					if er == *b.EvidenceRef {
						found = true
					}
				}
			}
			if !found {
				return storeError(CodeDerivedInvalidInput, "governance basis is unavailable")
			}
		default:
			return storeError(CodeDerivedInvalidInput, "governance basis is invalid")
		}
	}
	return nil
}
